services:
  rabbitmq_service:
    container_name: rabbitmq_container
    env_file:
      - .env
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  fastapi_service:
    container_name: fastapi_container
    env_file:
      - .env
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbitmq_service
      - redis_service
    environment:
      - BROKER_URL='amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq_container:5672//'
      - RESULT_BACKEND=redis://redis_container:6379/0
    stdin_open: true
    tty: true
  redis_service:
    container_name: redis_container
    image: redis:7-bookworm
    env_file:
      - .env
    ports:
      - "6379:6379"
