---
name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
      - name: Run Tests
        env:
          BROKER_URL: "-"
        run: |
          pytest -vv --junitxml=junit/test-results.xml
